### ISSUE TITLE
TypeError in card.py

### ISSUE THREAD

**Issue by BreePeterson** [brucepeterson/testbridge#3]
C:\Users\trfy9>python E:\Programming\Projects\testbridge\Bridge\card.py
Not a callable module
Traceback (most recent call last):
  File "E:\Programming\Projects\testbridge\Bridge\card.py", line 75, in <module>
    debug()
  File "E:\Programming\Projects\testbridge\Bridge\card.py", line 60, in debug
    winner =  max(cardPlayA, key=comparitor.compare)
TypeError: compare() missing 1 required positional argument: 'otherCard'

**Comment by brucepeterson** [comment]
Fixed:
python3 uses __lt__ and __eq__
